#! /bin/sh

sxhkd &
xcompmgr -c -n &


bspc monitor DP-0 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII IX
bspc monitor HDMI-0 -d X

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a mpv state=floating sticky=on 

# bash /home/michael/.config/bspwm/bspwm_colors.sh &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#{,.common}bspc config presel_border_color "$color1"

pic=`find ~/Pictures/Wallpapers/ | sort -R | tail -1`
nitrogen --head=0 --set-zoom-fill $pic
nitrogen --head=1 --set-zoom-fill $pic 
nitrogen --head=2 --set-zoom-fill $pic

$HOME/.config/polybar/launch.sh
