#!/bin/bash

source "${HOME}/.config/env"
pgrep -x sxhkd > /dev/null || sxhkd &
monitor-setup

bspc config remove_unplugged_monitors true
monitors=($(bspc query -M | uniq))

# set colours to match pic
pic=$(find ~/Pictures/Wallpapers/ | sort -R | tail -1)
#flavours generate dark $pic && flavours apply generated
flavours apply horizon-dark

# TODO: refactor, this could be much better lol
nitrogen --head=0 --set-zoom-fill "$pic"
[[ "${#monitors[@]}" = 1 ]] && \
	bspc monitor "${monitors[0]}" -d 1 2 3 4 5 6 7 8 9 10
[[ "${#monitors[@]}" = 2 ]] && \
	bspc monitor "${monitors[0]}" -d 1 2 3 4 5 && \
	bspc monitor "${monitors[1]}" -d 6 7 8 9 10 && \
	nitrogen --head=1 --set-zoom-fill "$pic"
[[ "${#monitors[@]}" = 3 ]] && \
	bspc monitor "${monitors[0]}" -d 1 2 3 4 && \
	bspc monitor "${monitors[1]}" -d 5 6 7 && \
	bspc monitor "${monitors[2]}" -d 8 9 10 && \
	nitrogen --head=1 --set-zoom-fill "$pic" && \
	nitrogen --head=2 --set-zoom-fill "$pic"

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a mpv state=floating sticky=on
bspc rule -a start_floating state=floating

# Mice bindings
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

~/.config/bspwm/bspwm_colors.sh &
"$HOME/.xinitrc" &
